@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.inventory.AddProductController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2020599460 { 
   	label=inventory
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AddProductController1691664687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddProductController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   addProductErrorLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductFilterField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductMaxTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductMinTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductNameTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductPriceTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductSaveErrorLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductStockTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   addProductTableView: TableView&lt;Part&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   associatedPartTableView: TableView&lt;Part&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   associatedParts: ObservableList&lt;Part&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addProductAddButtonListener(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- addProductCancelButtonListener(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- addProductSaveButtonListener(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- addProductsSearchFieldListener(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- handlePartSearch()</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(url: URL, resourceBundle: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >- removeAssociatedPartButtonListener(event: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InHouse1691664687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InHouse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   machineId: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Outsourced1691664687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Outsourced</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   companyName: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Part1691664687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Part</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   max: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   min: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   price: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stock: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
AddProductController1691664687 -> Part1691664687[label="addProductTableView
[0..1]"];
AddProductController1691664687 -> Part1691664687[label="associatedPartTableView
[0..1]"];
AddProductController1691664687 -> Part1691664687[label="associatedParts
[0..*]"];
Part1691664687 -> InHouse1691664687[arrowhead=none, arrowtail=empty, dir=both];
Part1691664687 -> Outsourced1691664687[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml